# Generated by Django 6.0.1 on 2026-01-13 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_created_at_alter_product_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_products/'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('😡', 'Angry'), ('😐', 'Neutral'), ('🙂', 'Good'), ('😄', 'Happy'), ('😍', 'Loved')], max_length=5)),
                ('rating', models.IntegerField()),
                ('liked_points', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
