# Generated by Django 6.0.1 on 2026-01-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
